### ISSUE TITLE
Consider transferring to the disq-bio organization

### ISSUE THREAD

**Issue by heuermh** [disq-bio/disq-examples#1]
Ping @tomwhite

I wrote up the metadata for this repository as if it were under the disq-bio organization
https://github.com/disq-bio

I am willing to transfer this, if the disq-bio organization is willing to accept it.

**Comment by tomwhite** [comment]
That would be a great addition. Thanks @heuermh!

**Comment by heuermh** [comment]
Migrated to disq-bio organization.
